# Generated by Django 3.2.4 on 2023-09-27 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chef',
            name='name',
        ),
        migrations.AddField(
            model_name='chef',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='chef',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='family.chef'),
        ),
    ]
