# Generated by Django 3.2.4 on 2023-10-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0006_menuimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='chef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family.chef'),
        ),
    ]
